### ISSUE TITLE
align flavor naming (change `upstream-ce` to `upstream`)

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-sonarqube#39]
### Describe what should be investigated or refactored
align flavor naming (change `upstream-ce` to `upstream`)

### Additional context

Was there a reason -ce was added other than that Mike had originally implemented gitlab that way?

**Comment by naveensrinivasan** [comment]
@zachariahmiller  Is this just renaming the text from `upstream-ce` to `upstream`?

**Comment by zachariahmiller** [comment]
@naveensrinivasan My understanding is yes. It would be renaming the flavor to remove the -ce and updating the places it is passed into the UDS tasks/from the GitHub workflows.

I was hoping someone might be able to confirm that there was no other reason since Mike left. I don't think there was. As far as I'm concerned, make the changes, if ci passed drop a quick message in swf slack channel as an FYI of the rename and then we can merge it in. 

Anyone using this in a prod environment would be using the registry1 flavor so there is minimal to no risk of impacting anyone on delivery.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan My understanding is yes. It would be renaming the flavor to remove the -ce and updating the places it is passed into the UDS tasks/from the GitHub workflows.
> 
> I was hoping someone might be able to confirm that there was no other reason since Mike left. I don't think there was. As far as I'm concerned, make the changes, if ci passed drop a quick message in swf slack channel as an FYI of the rename and then we can merge it in.
> 
> Anyone using this in a prod environment would be using the registry1 flavor so there is minimal to no risk of impacting anyone on delivery.

Thank you!!

**Comment by naveensrinivasan** [comment]
Fixed by https://github.com/defenseunicorns/uds-package-sonarqube/pull/41
