### ISSUE TITLE
 [ADR] Select a backup solution for SonarQube

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-sonarqube#45]
### Is your feature request related to a problem? Please describe.
**As** Ashton **I want** to be able to backup SonarQube safely **so that** I can restore it easily in the event of a disaster.

### Describe the solution you'd like

We should identify and select solutions that are able to backup the SonarQube database, and then follows the recommendations for restoration:

https://docs.sonarsource.com/sonarqube/9.6/instance-administration/backup-and-restore/

These should be written in a simple ADR to capture why the final solution was chosen and a follow on implementation issue should be created.

### Additional context

We currently don't have set SLAs but should target a baseline to have something while we continue to experiment.

**Comment by zachariahmiller** [comment]
https://docs.sonarsource.com/sonarqube/latest/instance-administration/backup-and-restore/

In the absence of more specific guidance, use normal rds backup/restore practices

**Comment by oates** [comment]
closing this and tracking here instead https://github.com/defenseunicorns/uds-infrastructure/issues/600
