### ISSUE TITLE
Sonarqube: Integration with keycloak

### ISSUE THREAD

**Issue by oates** [defenseunicorns/uds-package-sonarqube#49]
As an app developer, I want to be logged into Sonarqube after I log into UDS.

**Comment by oates** [comment]
Currently blocked by Jeff Pepr work. No task to link to for that issue for now.

**Comment by oates** [comment]
blocked by https://github.com/defenseunicorns/uds-core/issues/263

**Comment by ericwyles** [comment]
Depends on https://github.com/defenseunicorns/uds-core/issues/326 (I'm picking that one up now)
