### ISSUE TITLE
Migrate to Upstream Chart

### ISSUE THREAD

**Issue by ericwyles** [defenseunicorns/uds-package-sonarqube#82]
We need to migrate to the upstream chart. 

### Additional context
Needs to be release 10.6.0 or greater to pick up changes to the liveness and readiness probes so the upstream chart can work with registry1 images.
- https://github.com/SonarSource/helm-chart-sonarqube
- https://github.com/SonarSource/helm-chart-sonarqube/pull/481

**Comment by oates** [comment]
@ericwyles found this in backlog and moving to "In Progress". Please close once your upstream fix is released

**Comment by Racer159** [comment]
@ericwyles https://github.com/SonarSource/helm-chart-sonarqube/releases/tag/sonarqube-10.6.0-sonarqube-dce-10.6.0

**Comment by ericwyles** [comment]
When we point this to the upstream chart it will be default still try to use this probes that don't work for registry1 images. To get around this we can now add this section to the registry1-values.yaml:

```livenessProbe:
  exec: null
  httpGet:
    path: /
    scheme: HTTP
    port: 9000
readinessProbe:
  exec: null
  httpGet:
    path: /api/system/status
    scheme: HTTP
    port: 9000
 ```
 
 That will override the probes to the behavior that the registry1 fork of the chart was delivering.
